### PR TITLE
Completed pry and fancy factory

### PR DESCRIPTION
**Pull request by yeoenggu**

### CODE REVIEW

**Comment by yeoenggu** [comment]
wth pry, there is less need for irb script like pretty print.
But pry does not support ruby 2.2 yet.  Comments?

**Comment by eliotsykes** [comment]
Pry doesn't support ruby 2.2? I'm surprised. What happened when you tried to use it?

An alternative debugger is byebug which might already be in your Gemfile: http://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-byebug-gem

**Comment by yeoenggu** [comment]
I check pry changelog ... latest version they support is 2.1 ... so far it still seem to work.  This would be one of the discussion area.

**Comment by eliotsykes** [comment]
Ok, sounds good

**Pull request closed without merging**
